### ISSUE TITLE
Prices of configurable products

### ISSUE THREAD

**Issue by rommelfreddy** [mageplaza/magento-2-seo#102]
#### Versions #: 
Magent CE 2.4.1
Mageplaza SEO 2.2.4

#### Edition (EE, CE, OS, etc): 
Magento CE

#### Expected behavior:
Price information for configurable products are correctly set as described by inchoo.
https://inchoo.net/online-marketing/seo-vs-ppc-structured-data-markup-product-variants/

#### Actual behavior:

Please have a look to the image

![Bildschirmfoto 2020-12-04 um 11 19 29](https://user-images.githubusercontent.com/15031079/101180947-8d3e0b00-364c-11eb-9f33-3721a4a3e297.png)

1. This price is the minimum price of the product (incl. special price) --> Should not be precent
2. This price is the minimum price of the product (excl. special price) --> Should be the lowest final price
3. this price is the price without the special price (but the product has a special price) --> should be the final price of the variant
4. this is the (correct) price display on the product detail page.
5. this is the (correct) special price display on the product detail page.
7. this is the (correct) price from the feed - incl.special price. (sorry - wrong product in the screenshot)

#### Preconditions
- Configurable products with different prices on the childs incl. special prices.

**Comment by giaphn** [comment]
Hi,
I'm Shox from Mageplaza. To solve your problem, please try download and replace this file:
- app/code/Mageplaza/Seo/Plugin/SeoRender.php

Then clear the cache and check again.

Link download: https://drive.google.com/file/d/1Y0SF9BGKV1XoKTjtTI-ulWw5PHIZwJ8c/view?usp=sharing

**Comment by giaphn** [comment]
Closed due no response within 7 days.

**Comment by rommelfreddy** [comment]
Hello @giaphn 
great ! This will fix the issue. 

When do you plan a release with that fix?

**Comment by rommelfreddy** [comment]
could you give me an update for this?

**Comment by themew** [comment]
Has this issue been fixed in the current version?  All configurable products are losing their schema price on Google and Google Merchant center is complaining that pricing isn't set.

**Comment by rommelfreddy** [comment]
No,issue has still not been resolved.
Current pull request 
https://github.com/mageplaza/magento-2-seo/pull/120

You can use composer patches to patch your Magento 
https://github.com/mageplaza/magento-2-seo/pull/120.patch
