### ISSUE TITLE
Can not add structured data

### ISSUE THREAD

**Issue by Userr017** [mageplaza/magento-2-seo#54]
Updated to the latest version mageplaza seo 1.4.1 to 2.0.0. Before the upgrade everything works correctly, but now when added a new product and open product url on the frontend page it will always show error for new products " There has been an error processing your request - Can not add structured data".  Old products urls works fine.

### Preconditions

1. Magento: 2.2.0
2. PHP: 7.0
3. MySQL: 5.6.37

### Steps to reproduce

1. enable Megeplaza_Core
2. enable Mageplaza_Seo
3. upgrade, compile, reindex, flush
4. Adding a new product
5. Open new product url
6. Error page - (There has been an error processing your request - Can not add structured data)
**Error log - public_html/var/report**
`{"0":"Can not add structured data","1":"#0 \/home\/user\/public_html\/app\/code\/Mageplaza\/Seo\/Plugin\/SeoRender.php(152): Mageplaza\\Seo\\Plugin\\SeoRender->showProductStructuredData()\n#1 \/home\/user\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(146): Mageplaza\\Seo\\Plugin\\SeoRender->afterRenderHeadContent(Object(Magento\\Framework\\View\\Page\\Config\\Renderer\\Interceptor), '<meta charset=\"...')\n#2 \/home\/user\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Page\\Config\\Renderer\\Interceptor->Magento\\Framework\\Interception\\{closure}()\n#3 \/home\/user\/public_html\/generated\/code\/Magento\/Framework\/View\/Page\/Config\/Renderer\/Interceptor.php(26): Magento\\Framework\\View\\Page\\Config\\Renderer\\Interceptor->___callPlugins('renderHeadConte...', Array, Array)\n#4 \/home\/user\/public_html\/vendor\/magento\/framework\/View\/Result\/Page.php(249): Magento\\Framework\\View\\Page\\Config\\Renderer\\Interceptor->renderHeadContent()\n#5 \/home\/user\/public_html\/vendor\/magento\/framework\/View\/Result\/Layout.php(170): Magento\\Framework\\View\\Result\\Page->render(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#6 \/home\/user\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(58): Magento\\Framework\\View\\Result\\Layout->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#7 \/home\/user\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(138): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callParent('renderResult', Array)\n#8 \/home\/user\/public_html\/vendor\/magento\/framework\/Interception\/Interceptor.php(153): Magento\\Framework\\View\\Result\\Page\\Interceptor->Magento\\Framework\\Interception\\{closure}(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#9 \/home\/user\/public_html\/generated\/code\/Magento\/Framework\/View\/Result\/Page\/Interceptor.php(39): Magento\\Framework\\View\\Result\\Page\\Interceptor->___callPlugins('renderResult', Array, Array)\n#10 \/home\/user\/public_html\/vendor\/magento\/framework\/App\/Http.php(139): Magento\\Framework\\View\\Result\\Page\\Interceptor->renderResult(Object(Magento\\Framework\\App\\Response\\Http\\Interceptor))\n#11 \/home\/user\/public_html\/vendor\/magento\/framework\/App\/Bootstrap.php(256): Magento\\Framework\\App\\Http->launch()\n#12 \/home\/user\/public_html\/index.php(39): Magento\\Framework\\App\\Bootstrap->run(Object(Magento\\Framework\\App\\Http))\n#13 {main}","url":"\/fi\/(product url)","script_name":"\/index.php"}`

### Expected result

It should be open new added products without any problems on frontend page.

### Actual result

It show error page - There has been an error processing your request (Can not add structured data)

**Comment by Userr017** [comment]
Do you have anything idea solve this problem?

**Comment by shoutcast2** [comment]
I am having the same issue.. I think it may be related to MagePlaza free Seo.  Did you find a solution?

**Comment by shoutcast2** [comment]
So I uninstalled Mageplaza Seo and it fixed the issue..

**Comment by haitv282** [comment]
Hi there,

The problem has been solved on our latest version 2.0.1. Please upgrade the extension and check it again.
Thank you very much.

**Comment by DannyW87** [comment]
Thanks @haitv282. Are you able to update composer to allow packagist to update?

**Comment by RetailExpress** [comment]
We have updated to 2.0.1 of the MagePlaza SEO free and core but still have this issue. We are running Magento 2.1.9

**Comment by BabliDey** [comment]
I am using Magento 2.1.8 and updated the package version to 2.0.1 but still having the same issue.
![1](https://user-images.githubusercontent.com/24405051/34558109-bd190302-f162-11e7-9edd-43c33579fade.png
<img width="1170" alt="bildschirmfoto 2018-01-04 um 07 54 44" src="https://user-images.githubusercontent.com/24405051/34558118-ccca7a38-f162-11e7-921e-a498f4b8b02f.png">
)

**Comment by afavata** [comment]
My suggest is to uninstall core and SEO from the wizard panel and then install the 2 modules through composer.
I'm at Magento 2.2.1 with the last version of mageplaza core and SEO and all works perfectly.
I use to install all the modules with composer
Hope I was of help
